[package]
name = "fn_time"
version = "0.1.0"
authors = ["Tom Gowan <s3549186@student.rmit.edu.au>"]

[dependencies]
serde = "1.0.68"
serde_json = "1.0.22"
serde_derive = "1.0.68"

[dev-dependencies]
rand = "0.5"
